backend:
  name: github
  repo: mozzart-games/mozzartgames.github.io
  branch: main
  # base_url musi wskazywać na Netlify, by obsłużyć OAuth
  base_url: https://mozzartstore.netlify.app
  site_domain: mozzart-games.github.io

# Ustawienia Identity
publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Treść", name: "body", widget: "markdown"}
