backend:
  name: github
  repo: mozzart-games/mozzartgames.github.io
  branch: main
  site_domain: mozzartstore.netlify.app # To jest Twoja nowa nazwa z obrazka image_e18a67.png

media_folder: "assets/images" # Tu będą trafiać zdjęcia Twojego merchu
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Posty / Drop Merchu"
    folder: "_posts"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Treść", name: "body", widget: "markdown"}
