backend:
  name: github
  repo: mozzart-games/mozzartgames.github.io
  branch: main
  # To jest najważniejsza zmiana:
  auth_type: implicit

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Treść", name: "body", widget: "markdown"}